spring:
    application:
        name: spring-keycloak
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/realms/user-info
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
    port: 8080

