spring:
    application:
        name: spring-keycloak
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8081/realms/user-info
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
    datasource:
        url: jdbc:h2:mem:db
        username: sa
        password: secret
        driverClassName: org.h2.Driver
        jpa:
            database-platform: org.hibernate.dialect.H2Dialect
            hibernate:
                ddl-auto: update
    
    jpa:
        defer-datasource-initialization: true
        show-sql: true

    h2:
        console:
            enabled: true

server:
    port: 8080

